# Generated by Django 5.2.4 on 2025-07-11 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0004_alter_order_date_alter_orderitem_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='menuitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LittleLemonAPI.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='LittleLemonAPI.order'),
        ),
    ]
